const avesArgentinas = [
  {
    id: 1,
    nombre: "Loro Barranquero",
    especie: "Cyanoliseus patagonus",
    colores: ["Verde", "Azul", "Amarillo", "Naranja"],
  },
  {
    id: 2,
    nombre: "Cóndor Andino",
    especie: "Vultur gryphus",
    colores: ["Negro"],
  },
  {
    id: 3,
    nombre: "Cardenal Amarillo",
    especie: "Gubernatrix cristata",
    colores: ["Amarillo", "Negro"],
  },
  {
    id: 4,
    nombre: "Hornero",
    especie: "Furnarius rufus",
    colores: ["Marrón", "Blanco"],
  },
  {
    id: 5,
    nombre: "Yal",
    especie: "Gubernatrix cristata",
    colores: ["Negro", "Amarillo"],
  },
  {
    id: 6,
    nombre: "Gaviota Cahuil",
    especie: "Larus maculipennis",
    colores: ["Blanco", "Gris"],
  },
  {
    id: 7,
    nombre: "Carancho",
    especie: "Caracara plancus",
    colores: ["Marrón", "Blanco", "Negro"],
  },
  {
    id: 8,
    nombre: "Chimango",
    especie: "Milvago chimango",
    colores: ["Gris", "Blanco"],
  },
  {
    id: 9,
    nombre: "Cotorra Argentina",
    especie: "Myiopsitta monachus",
    colores: ["Verde", "Amarillo"],
  },
  {
    id: 10,
    nombre: "Lechuza Vizcachera",
    especie: "Athene cunicularia",
    colores: ["Blanco", "Marrón"],
  },
  {
    id: 11,
    nombre: "Martín Pescador",
    especie: "Chloroceryle americana",
    colores: ["Verde", "Blanco"],
  },
  {
    id: 12,
    nombre: "Pato Crestón",
    especie: "Lophonetta specularioides",
    colores: ["Blanco", "Negro", "Gris"],
  },
  {
    id: 13,
    nombre: "Picaflor Común",
    especie: "Chlorostilbon aureoventris",
    colores: ["Verde", "Amarillo"],
  },
  {
    id: 14,
    nombre: "Chirigüe Aterciopelado",
    especie: "Elania poliocephala",
    colores: ["Gris", "Blanco"],
  },
  {
    id: 15,
    nombre: "Calandria Grande",
    especie: "Mimus saturninus",
    colores: ["Gris", "Blanco"],
  },
  {
    id: 16,
    nombre: "Carpintero Real",
    especie: "Colaptes melanochloros",
    colores: ["Negro", "Blanco", "Marrón"],
  },
];
