const pokemonArray = [
  {
    nombre: "Pikachu",
    tipo: "Eléctrico",
    altura: 0.4,
    peso: 6,
    habilidades: ["Electricidad estática", "Pararrayos"],
    debilidades: ["Tierra"],
  },
  {
    nombre: "Charizard",
    tipo: "Fuego/Volador",
    altura: 1.7,
    peso: 90.5,
    habilidades: ["Mar Llamas", "Poder Solar"],
    debilidades: ["Agua", "Eléctrico", "Roca"],
  },
  {
    nombre: "Bulbasaur",
    tipo: "Planta/Veneno",
    altura: 0.7,
    peso: 6.9,
    habilidades: ["Espesura", "Clorofila"],
    debilidades: ["Fuego", "Hielo", "Volador", "Psíquico"],
  },
  {
    nombre: "Squirtle",
    tipo: "Agua",
    altura: 0.5,
    peso: 9,
    habilidades: ["Torrente", "Cura Lluvia"],
    debilidades: ["Eléctrico", "Planta"],
  },
  {
    nombre: "Jigglypuff",
    tipo: "Normal/Hada",
    altura: 0.5,
    peso: 5.5,
    habilidades: ["Voz Dulce", "Gran Encanto"],
    debilidades: ["Acero", "Veneno"],
  },
  {
    nombre: "Gengar",
    tipo: "Fantasma/Veneno",
    altura: 1.5,
    peso: 40.5,
    habilidades: ["Levitación", "Cuerpo Maldito"],
    debilidades: ["Psíquico", "Tierra", "Fantasma"],
  },
  {
    nombre: "Machop",
    tipo: "Lucha",
    altura: 0.8,
    peso: 19.5,
    habilidades: ["Agallas", "Impulso"],
    debilidades: ["Volador", "Psíquico", "Hada"],
  },
  {
    nombre: "Gyarados",
    tipo: "Agua/Volador",
    altura: 6.5,
    peso: 235,
    habilidades: ["Intimidación", "Nado Rápido"],
    debilidades: ["Eléctrico", "Roca"],
  },
  {
    nombre: "Mewtwo",
    tipo: "Psíquico",
    altura: 2,
    peso: 122,
    habilidades: ["Presión", "Experto"],
    debilidades: ["Bicho", "Fantasma", "Oscuridad"],
  },
  {
    nombre: "Greninja",
    tipo: "Agua/Siniestro",
    altura: 1.5,
    peso: 40,
    habilidades: ["Torrente", "Protean"],
    debilidades: ["Eléctrico", "Lucha", "Planta", "Hada"],
  },
  {
    nombre: "Lucario",
    tipo: "Lucha/Acero",
    altura: 1.2,
    peso: 54,
    habilidades: ["Impasible", "Justiciero"],
    debilidades: ["Fuego", "Lucha", "Tierra"],
  },
  {
    nombre: "Eevee",
    tipo: "Normal",
    altura: 0.3,
    peso: 6.5,
    habilidades: ["Fuga", "Adaptable"],
    debilidades: ["Lucha"],
  },
  {
    nombre: "Snorlax",
    tipo: "Normal",
    altura: 2.1,
    peso: 460,
    habilidades: ["Indefenso", "Insonorizar"],
    debilidades: ["Lucha"],
  },
  {
    nombre: "Gardevoir",
    tipo: "Psíquico/Hada",
    altura: 1.6,
    peso: 48.4,
    habilidades: ["Sincronía", "Rastro"],
    debilidades: ["Acero", "Veneno"],
  },
  {
    nombre: "Rayquaza",
    tipo: "Dragón/Volador",
    altura: 7,
    peso: 206.5,
    habilidades: ["Presión"],
    debilidades: ["Hielo", "Roca"],
  },
];
